Insert into cidade (codigo_ibge, nome, uf) values ('3500105','Adamantina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500204','Adolfo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500303','Aguaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500402','Águas da Prata', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500501','Águas de Lindóia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500550','Águas de Santa Bárbara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500600','Águas de São Pedro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500709','Agudos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500758','Alambari', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500808','Alfredo Marcondes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3500907','Altair', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501004','Altinópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501103','Alto Alegre', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501152','Alumínio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501202','Álvares Florence', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501301','Álvares Machado', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501400','Álvaro de Carvalho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501509','Alvinlândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501608','Americana', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501707','Américo Brasiliense', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501806','Américo de Campos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3501905','Amparo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502002','Analândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502101','Andradina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502200','Angatuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502309','Anhembi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502408','Anhumas', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502507','Aparecida', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502606','Aparecida D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502705','Apiaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502754','Araçariguama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502804','Araçatuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3502903','Araçoiaba da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503000','Aramina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503109','Arandu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503158','Arapeí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503208','Araraquara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503307','Araras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503356','Arco-Íris', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503406','Arealva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503505','Areias', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503604','Areiópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503703','Ariranha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503802','Artur Nogueira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503901','Arujá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3503950','Aspásia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504008','Assis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504107','Atibaia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504206','Auriflama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504305','Avaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504404','Avanhandava', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504503','Avaré', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504602','Bady Bassitt', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504701','Balbinos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504800','Bálsamo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3504909','Bananal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505005','Barão de Antonina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505104','Barbosa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505203','Bariri', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505302','Barra Bonita', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505351','Barra do Chapéu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505401','Barra do Turvo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505500','Barretos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505609','Barrinha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505708','Barueri', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505807','Bastos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3505906','Batatais', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506003','Bauru', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506102','Bebedouro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506201','Bento de Abreu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506300','Bernardino de Campos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506359','Bertioga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506409','Bilac', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506508','Birigui', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506607','Biritiba-Mirim', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506706','Boa Esperança do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506805','Bocaina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3506904','Bofete', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507001','Boituva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507100','Bom Jesus dos Perdões', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507159','Bom Sucesso de Itararé', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507209','Borá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507308','Boracéia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507407','Borborema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507456','Borebi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507506','Botucatu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507605','Bragança Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507704','Braúna', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507753','Brejo Alegre', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507803','Brodowski', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3507902','Brotas', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508009','Buri', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508108','Buritama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508207','Buritizal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508306','Cabrália Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508405','Cabreúva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508504','Caçapava', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508603','Cachoeira Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508702','Caconde', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508801','Cafelândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3508900','Caiabu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509007','Caieiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509106','Caiuá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509205','Cajamar', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509254','Cajati', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509304','Cajobi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509403','Cajuru', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509452','Campina do Monte Alegre', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509502','Campinas', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509601','Campo Limpo Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509700','Campos do Jordão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509809','Campos Novos Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509908','Cananéia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3509957','Canas', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510005','Cândido Mota', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510104','Cândido Rodrigues', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510153','Canitar', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510203','Capão Bonito', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510302','Capela do Alto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510401','Capivari', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510500','Caraguatatuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510609','Carapicuíba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510708','Cardoso', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510807','Casa Branca', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3510906','Cássia dos Coqueiros', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511003','Castilho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511102','Catanduva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511201','Catiguá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511300','Cedral', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511409','Cerqueira César', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511508','Cerquilho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511607','Cesário Lange', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511706','Charqueada', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3511904','Clementina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512001','Colina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512100','Colômbia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512209','Conchal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512308','Conchas', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512407','Cordeirópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512506','Coroados', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512605','Coronel Macedo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512704','Corumbataí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512803','Cosmópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3512902','Cosmorama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513009','Cotia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513108','Cravinhos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513207','Cristais Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513306','Cruzália', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513405','Cruzeiro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513504','Cubatão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513603','Cunha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513702','Descalvado', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513801','Diadema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513850','Dirce Reis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3513900','Divinolândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514007','Dobrada', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514106','Dois Córregos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514205','Dolcinópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514304','Dourado', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514403','Dracena', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514502','Duartina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514601','Dumont', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514700','Echaporã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514809','Eldorado', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514908','Elias Fausto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514924','Elisiário', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3514957','Embaúba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515004','Embu das Artes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515103','Embu-Guaçu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515129','Emilianópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515152','Engenheiro Coelho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515186','Espírito Santo do Pinhal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515194','Espírito Santo do Turvo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515202','Estrela D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515301','Estrela do Norte', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515350','Euclides da Cunha Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515400','Fartura', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515509','Fernandópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515608','Fernando Prestes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515657','Fernão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515707','Ferraz de Vasconcelos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515806','Flora Rica', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3515905','Floreal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516002','Flórida Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516101','Florínia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516200','Franca', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516309','Francisco Morato', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516408','Franco da Rocha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516507','Gabriel Monteiro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516606','Gália', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516705','Garça', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516804','Gastão Vidigal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516853','Gavião Peixoto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3516903','General Salgado', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517000','Getulina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517109','Glicério', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517208','Guaiçara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517307','Guaimbê', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517406','Guaíra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517505','Guapiaçu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517604','Guapiara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517703','Guará', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517802','Guaraçaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3517901','Guaraci', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518008','Guarani D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518107','Guarantã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518206','Guararapes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518305','Guararema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518404','Guaratinguetá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518503','Guareí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518602','Guariba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518701','Guarujá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518800','Guarulhos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518859','Guatapará', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3518909','Guzolândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519006','Herculândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519055','Holambra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519071','Hortolândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519105','Iacanga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519204','Iacri', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519253','Iaras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519303','Ibaté', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519402','Ibirá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519501','Ibirarema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519600','Ibitinga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519709','Ibiúna', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519808','Icém', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3519907','Iepê', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520004','Igaraçu do Tietê', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520103','Igarapava', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520202','Igaratá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520301','Iguape', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520400','Ilhabela', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520426','Ilha Comprida', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520442','Ilha Solteira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520509','Indaiatuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520608','Indiana', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520707','Indiaporã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520806','Inúbia Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3520905','Ipaussu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521002','Iperó', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521101','Ipeúna', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521150','Ipiguá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521200','Iporanga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521309','Ipuã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521408','Iracemápolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521507','Irapuã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521606','Irapuru', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521705','Itaberá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521804','Itaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3521903','Itajobi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522000','Itaju', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522109','Itanhaém', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522158','Itaóca', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522208','Itapecerica da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522307','Itapetininga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522406','Itapeva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522505','Itapevi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522604','Itapira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522653','Itapirapuã Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522703','Itápolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522802','Itaporanga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3522901','Itapuí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523008','Itapura', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523107','Itaquaquecetuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523206','Itararé', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523305','Itariri', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523404','Itatiba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523503','Itatinga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523602','Itirapina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523701','Itirapuã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523800','Itobi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3523909','Itu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524006','Itupeva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524105','Ituverava', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524204','Jaborandi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524303','Jaboticabal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524402','Jacareí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524501','Jaci', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524600','Jacupiranga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524709','Jaguariúna', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524808','Jales', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3524907','Jambeiro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525003','Jandira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525102','Jardinópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525201','Jarinu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525300','Jaú', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525409','Jeriquara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525508','Joanópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525607','João Ramalho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525706','José Bonifácio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525805','Júlio Mesquita', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525854','Jumirim', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3525904','Jundiaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526001','Junqueirópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526100','Juquiá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526209','Juquitiba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526308','Lagoinha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526407','Laranjal Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526506','Lavínia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526605','Lavrinhas', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526704','Leme', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526803','Lençóis Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3526902','Limeira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527009','Lindóia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527108','Lins', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527207','Lorena', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527256','Lourdes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527306','Louveira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527405','Lucélia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527504','Lucianópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527603','Luís Antônio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527702','Luiziânia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527801','Lupércio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3527900','Lutécia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528007','Macatuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528106','Macaubal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528205','Macedônia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528304','Magda', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528403','Mairinque', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528502','Mairiporã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528601','Manduri', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528700','Marabá Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528809','Maracaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528858','Marapoama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3528908','Mariápolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529005','Marília', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529104','Marinópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529203','Martinópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529302','Matão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529401','Mauá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529500','Mendonça', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529609','Meridiano', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529658','Mesópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529708','Miguelópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529807','Mineiros do Tietê', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3529906','Miracatu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530003','Mira Estrela', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530102','Mirandópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530201','Mirante do Paranapanema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530300','Mirassol', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530409','Mirassolândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530508','Mococa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530607','Mogi das Cruzes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530706','Mogi Guaçu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530805','Moji Mirim', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3530904','Mombuca', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531001','Monções', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531100','Mongaguá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531209','Monte Alegre do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531308','Monte Alto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531407','Monte Aprazível', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531506','Monte Azul Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531605','Monte Castelo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531704','Monteiro Lobato', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531803','Monte Mor', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3531902','Morro Agudo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532009','Morungaba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532058','Motuca', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532108','Murutinga do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532157','Nantes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532207','Narandiba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532306','Natividade da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532405','Nazaré Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532504','Neves Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532603','Nhandeara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532702','Nipoã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532801','Nova Aliança', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532827','Nova Campina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532843','Nova Canaã Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532868','Nova Castilho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3532900','Nova Europa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533007','Nova Granada', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533106','Nova Guataporanga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533205','Nova Independência', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533254','Novais', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533304','Nova Luzitânia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533403','Nova Odessa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533502','Novo Horizonte', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533601','Nuporanga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533700','Ocauçu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533809','Óleo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3533908','Olímpia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534005','Onda Verde', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534104','Oriente', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534203','Orindiúva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534302','Orlândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534401','Osasco', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534500','Oscar Bressane', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534609','Osvaldo Cruz', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534708','Ourinhos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534757','Ouroeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534807','Ouro Verde', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3534906','Pacaembu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535002','Palestina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535101','Palmares Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535200','Palmeira D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535309','Palmital', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535408','Panorama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535507','Paraguaçu Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535606','Paraibuna', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535705','Paraíso', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535804','Paranapanema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3535903','Paranapuã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536000','Parapuã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536109','Pardinho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536208','Pariquera-Açu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536257','Parisi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536307','Patrocínio Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536406','Paulicéia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536505','Paulínia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536570','Paulistânia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536604','Paulo de Faria', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536703','Pederneiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536802','Pedra Bela', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3536901','Pedranópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537008','Pedregulho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537107','Pedreira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537156','Pedrinhas Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537206','Pedro de Toledo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537305','Penápolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537404','Pereira Barreto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537503','Pereiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537602','Peruíbe', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537701','Piacatu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537800','Piedade', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3537909','Pilar do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538006','Pindamonhangaba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538105','Pindorama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538204','Pinhalzinho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538303','Piquerobi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538501','Piquete', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538600','Piracaia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538709','Piracicaba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538808','Piraju', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3538907','Pirajuí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539004','Pirangi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539103','Pirapora do Bom Jesus', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539202','Pirapozinho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539301','Pirassununga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539400','Piratininga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539509','Pitangueiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539608','Planalto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539707','Platina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539806','Poá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3539905','Poloni', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540002','Pompéia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540101','Pongaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540200','Pontal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540259','Pontalinda', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540309','Pontes Gestal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540408','Populina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540507','Porangaba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540606','Porto Feliz', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540705','Porto Ferreira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540754','Potim', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540804','Potirendaba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540853','Pracinha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3540903','Pradópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541000','Praia Grande', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541059','Pratânia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541109','Presidente Alves', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541208','Presidente Bernardes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541307','Presidente Epitácio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541406','Presidente Prudente', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541505','Presidente Venceslau', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541604','Promissão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541653','Quadra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541703','Quatá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541802','Queiroz', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3541901','Queluz', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542008','Quintana', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542107','Rafard', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542206','Rancharia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542305','Redenção da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542404','Regente Feijó', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542503','Reginópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542602','Registro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542701','Restinga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542800','Ribeira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3542909','Ribeirão Bonito', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543006','Ribeirão Branco', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543105','Ribeirão Corrente', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543204','Ribeirão do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543238','Ribeirão dos Índios', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543253','Ribeirão Grande', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543303','Ribeirão Pires', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543402','Ribeirão Preto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543501','Riversul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543600','Rifaina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543709','Rincão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543808','Rinópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3543907','Rio Claro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544004','Rio das Pedras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544103','Rio Grande da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544202','Riolândia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544251','Rosana', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544301','Roseira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544400','Rubiácea', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544509','Rubinéia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544608','Sabino', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544707','Sagres', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544806','Sales', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3544905','Sales Oliveira', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545001','Salesópolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545100','Salmourão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545159','Saltinho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545209','Salto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545308','Salto de Pirapora', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545407','Salto Grande', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545506','Sandovalina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545605','Santa Adélia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545704','Santa Albertina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3545803','Santa Bárbara D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546009','Santa Branca', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546108','Santa Clara D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546207','Santa Cruz da Conceição', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546256','Santa Cruz da Esperança', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546306','Santa Cruz das Palmeiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546405','Santa Cruz do Rio Pardo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546504','Santa Ernestina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546603','Santa Fé do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546702','Santa Gertrudes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546801','Santa Isabel', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3546900','Santa Lúcia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547007','Santa Maria da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547106','Santa Mercedes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547205','Santana da Ponte Pensa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547304','Santana de Parnaíba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547403','Santa Rita D''Oeste', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547502','Santa Rita do Passa Quatro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547601','Santa Rosa de Viterbo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547650','Santa Salete', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547700','Santo Anastácio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547809','Santo André', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3547908','Santo Antônio da Alegria', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548005','Santo Antônio de Posse', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548054','Santo Antônio do Aracanguá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548104','Santo Antônio do Jardim', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548203','Santo Antônio do Pinhal', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548302','Santo Expedito', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548401','Santópolis do Aguapeí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548500','Santos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548609','São Bento do Sapucaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548708','São Bernardo do Campo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548807','São Caetano do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3548906','São Carlos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549003','São Francisco', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549102','São João da Boa Vista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549201','São João das Duas Pontes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549250','São João de Iracema', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549300','São João do Pau D''Alho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549409','São Joaquim da Barra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549508','São José da Bela Vista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549607','São José do Barreiro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549706','São José do Rio Pardo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549805','São José do Rio Preto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549904','São José dos Campos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3549953','São Lourenço da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550001','São Luís do Paraitinga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550100','São Manuel', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550209','São Miguel Arcanjo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550308','São Paulo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550407','São Pedro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550506','São Pedro do Turvo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550605','São Roque', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550704','São Sebastião', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550803','São Sebastião da Grama', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3550902','São Simão', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551009','São Vicente', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551108','Sarapuí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551207','Sarutaiá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551306','Sebastianópolis do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551405','Serra Azul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551504','Serrana', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551603','Serra Negra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551702','Sertãozinho', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551801','Sete Barras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3551900','Severínia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552007','Silveiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552106','Socorro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552205','Sorocaba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552304','Sud Mennucci', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552403','Sumaré', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552502','Suzano', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552551','Suzanápolis', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552601','Tabapuã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552700','Tabatinga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552809','Taboão da Serra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3552908','Taciba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553005','Taguaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553104','Taiaçu', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553203','Taiúva', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553302','Tambaú', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553401','Tanabi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553500','Tapiraí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553609','Tapiratiba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553658','Taquaral', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553708','Taquaritinga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553807','Taquarituba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553856','Taquarivaí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553906','Tarabai', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3553955','Tarumã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554003','Tatuí', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554102','Taubaté', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554201','Tejupá', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554300','Teodoro Sampaio', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554409','Terra Roxa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554508','Tietê', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554607','Timburi', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554656','Torre de Pedra', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554706','Torrinha', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554755','Trabiju', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554805','Tremembé', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554904','Três Fronteiras', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3554953','Tuiuti', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555000','Tupã', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555109','Tupi Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555208','Turiúba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555307','Turmalina', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555356','Ubarana', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555406','Ubatuba', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555505','Ubirajara', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555604','Uchoa', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555703','União Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555802','Urânia', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3555901','Uru', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556008','Urupês', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556107','Valentim Gentil', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556206','Valinhos', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556305','Valparaíso', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556354','Vargem', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556404','Vargem Grande do Sul', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556453','Vargem Grande Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556503','Várzea Paulista', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556602','Vera Cruz', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556701','Vinhedo', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556800','Viradouro', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556909','Vista Alegre do Alto', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3556958','Vitória Brasil', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3557006','Votorantim', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3557105','Votuporanga', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3557154','Zacarias', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3557204','Chavantes', 'SP');
Insert into cidade (codigo_ibge, nome, uf) values ('3557303','Estiva Gerbi', 'SP');